apiVersion: v1
kind: Pod
metadata:
labels:
    component: ci
spec:
    serviceAccountName: jenkins
    containers:
      - image: catrobat/catrobat-android:stable
        name: catroid
        env:
          - name: "ANDROID_SDK_ROOT"
            value: "/home/user/android/sdk"
          - name: "ANDROID_AVD_HOME"
            value: "/home/user/avds"
        tty: true
        resources:
          limits:
            - memory: 6Gi
              cpu: 4
        volumeMounts:
          - mountPath: /dev/kvm
            name: dev-kvm
        securityContext:
            privileged: true
    volumes:
      - name: dev-kvm
        hostPath:
          path: /dev/kvm
    # nodeSelector:
    #     device: kvm
    # nodeSelector:
    # device: kvm-ui